### ISSUE TITLE
Seed+fertilizers

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [loki79uk/FS19_BulkFill#1]
Hey. There is a problem with seed filling if there is a pallet of fertilizers nearby. I selected the seed pan as active, but the Fill command does not work. If the planter does not have a fertilizer hopper, this does not happen. Or it is necessary to drive further away so that fertilizers do not fall into the coverage area.

**Comment by Gonimy-Vetrom** [comment]
It happens in this position and with such equipment. But this is rare. More often than not, everything works well.
![fsScreen_2021_01_18_20_45_54](https://user-images.githubusercontent.com/8200153/104953064-622a3380-59ce-11eb-913e-3eeb41d7e1d3.png)

**Comment by loki79uk** [comment]
Thank you, this is really usefull.  I will try to reproduce it now.

**Comment by loki79uk** [comment]
I believe that this is a base game issue.  If you load the game without the BulkFill mod selected, then you cannot load fertiliser before seeds in this position.  Furthermore, you must have the seeds compartment cover open.  If the fertliser cover is open, then nothing is loaded.  I can certainly try to improve this behaviour.  Thank you again for finding it.

**Comment by loki79uk** [comment]
For now I've just added some colour coding to the selected items to make it clear what is going on.
Yellow = Standard
Green = MultiFill Correct Type
Red  = MultiFill WrongType

You still must open the correct cover for the fill type that you want to fill.  I can probably make the correct cover open for each selected item, but I need to think about it a bit more.  Maybe it is better to select from the matching fill types only, but I think prefer the first option (to open the correct cover).

**Comment by loki79uk** [comment]
Latest version (beta.3) will open the correct cover to match the selected fill type.  I have left the colour coding in for potential debugging purposes, but now the selected items should always be green, unless all compartments are full (then it will be red).
