### ISSUE TITLE
Refuel the tractor from a trailer 

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [loki79uk/FS19_BulkFill#4]
When I want to refuel the tractor from a trailer with a barrel, I cannot do this and there is an error.
FS19_BulkFill/BulkFill.lua:379: attempt to index local 'bf' (a nil value)

**Comment by Gonimy-Vetrom** [comment]
![fsScreen_2021_01_27_22_09_06](https://user-images.githubusercontent.com/8200153/106047550-6a7c2000-60ec-11eb-9076-e96ba0d87ce3.png)

**Comment by loki79uk** [comment]
Thanks for letting me know.  Can you try beta.8 please?  https://github.com/loki79uk/BulkFill/releases/tag/v1.0.0.0-beta

**Comment by Gonimy-Vetrom** [comment]
It works now. Thank you.
